version: '3'

services:
  kali-build:
    privileged: true
    build:
      context: docker
    volumes:
    - ./variant-xfce-custom:/variant-xfce-custom
    - ./output:/output
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined

