version: '3'

services:
  kali-build:
    build:
      context: docker
    environment:
    - DEBIAN_FRONTEND=noninteractive
    - DEBIAN_FRONTEND=teletype
    - ACCEPT_EULA=Y
    volumes:
    - ./variant-xfce-custom:/variant-xfce-custom
    - ./output:/output
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined

